WIP: Changing commands for new 6.6 kernel IOCTL structure
virtee/snphost pull request #32
Opened 2024-02-07 21:40 UTC by DGonzalezVillal

WIP: Waiting until library fixes and new release is cut. Docs update missing

Changing the way commands broken by the 6.6 kernel update work. 

IMPORT: Will convert a cert chain into kernel formatted cert struct and place the bytes into a file. This file can be provided to QEMU through the new certs-path flag in order to do extended attestation

EXPORT: Will convert a kernel formatted cert file into a cert chain and place the certs in a directory.

CONFIG: modify the SNP platform configuration
   -SET: User has to provide they're desired TCB values and Mask Chip value, then new config will be set
   -RESET: Provides 0s to Config. This will return the machine to the last committed Config version

COMMIT: Commit the current TCB and FW versions to the PSP. WILL NOT ALLOW ROLLBACKS TO OLDER VERSIONS.

2024-02-08 16:49 UTC, larrydewey requested changes

2024-02-08 16:49 UTC, larrydewey commented on src/cert/export.rs
> +}
Any reason we are doing a move (copy) of cert_bytes for each step here? Would it make sense to do something like this:

```suggestion
fn cert_entries(cert_bytes: &[u8]) -> Result<Vec<CertTableEntry>> {
    let certs = CertTableEntry::vec_bytes_to_cert_table(cert_bytes)
        .context("Could not convert bytes to certs")?;
    Ok(certs)
}
```

2024-02-22 21:38 UTC, larrydewey approved these changes

2024-02-22 21:38 UTC, larrydewey commented on src/cert/import.rs
> +        .context("Failed to convert certificates to GHCB formatted bytes.")?;
```suggestion
        .context("Failed to convert certificates to GHCB bytes specification.")?;
```

2024-02-22 22:39 UTC, DGonzalezVillal commented
Also added vlek and der support to this PR

2024-02-23 20:02 UTC, larrydewey approved these changes

2024-03-02 01:10 UTC, tylerfanelli approved these changes

2024-03-02 01:10 UTC, merged