Remove strict semvar for clap dependency
virtee/snphost pull request #74
Opened 2024-08-30 17:34 UTC by CookieComputing

In a related note to https://github.com/virtee/snpguest/issues/68, removes the strict dependency versioning on `clap`

2024-08-30 18:30 UTC, tylerfanelli commented
Can you add a `Signed-off-by` line to the commits? Also there seems to be a `clippy` issue

2024-08-30 18:56 UTC, CookieComputing commented
Ah, the clippy issue is coming down to the MSRV problem I addressed in the issue :\ 

```
[rustc 1.74 or newer, while the currently active rustc version is 1.70.0](error: package `clap_lex v0.7.2` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.70.0)
```

2024-08-30 19:00 UTC, tylerfanelli commented
We usually try to stay in line with what major distros are using. I think an update to 1.74 (maybe even 1.8?) is fine.

2024-08-30 19:01 UTC, tylerfanelli commented
@larrydewey are you alright with updating?

2024-09-05 18:37 UTC, larrydewey commented
Can we bump this to 1.80, instead?

![image](https://github.com/user-attachments/assets/39a16092-ffc8-4f80-841e-dc2424790a0f)

2024-09-05 18:37 UTC, tylerfanelli requested changes

2024-09-05 18:37 UTC, tylerfanelli commented on Cargo.toml
> +rust-version = "1.74"
```suggestion
rust-version = "1.79"
```

2024-09-05 18:39 UTC, tylerfanelli requested changes

2024-09-05 18:39 UTC, tylerfanelli commented on Cargo.toml
> +rust-version = "1.74"
```suggestion
rust-version = "1.80"
```

2024-09-05 19:15 UTC, tylerfanelli approved these changes

2024-09-05 19:15 UTC, merged